---
title: "Difference-in-Differences Regressions"
output: html_notebook
---

This is a notebook that runs the regressions for all of the difference-in-differences
regressions for my honors thesis project. 

```{r libraries}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(stargazer)
library(plm)
library(regclass)
```

Importing Relevant Datasets: 

```{r data}
# Wage Datasets
pa_wage <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/physicians_aides_wage_single.csv",header =  TRUE)
sa_wage <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/secretary_aides_wage_single.csv",header =  TRUE)

# Employment Datasets
pa_emp <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/physicians_aides_emp_single.csv",header =  TRUE)
sa_emp <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/secretary_aides_emp_single.csv",header =  TRUE)
```

Physicians DiD Regressions: 

```{r physicians}
# Wage DiD for Physicians vs. Aides
pa_wage_did1 <- lm(LOGWAGE ~ AI + AIPost + factor(YEAR) + factor(IND1990), data = pa_wage)
pa_wage_did2 <- lm(LOGWAGE ~ AI + AIPost + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(YEAR) + factor(IND1990), data = pa_wage) 

# Employment DiD for Secretaries vs. Aides
pa_emp_did1 <- lm(LOGEMP ~ AI + AIPost + factor(YEAR) + factor(IND1990), data = pa_emp)
pa_emp_did2 <- lm(LOGEMP ~ AI + AIPost + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(YEAR) + factor(IND1990), data = pa_emp)
```

```{r physicians2}
summary(pa_emp_did2)
```


```{r stargazer1, echo = TRUE, message=FALSE, warning=FALSE, results='asis'}
stargazer(pa_wage_did1, pa_wage_did2, pa_emp_did1, pa_emp_did2,
          type = "latex", header=FALSE, 
          column.sep.width = "0.1pt",
          omit.stat =c("f", "ser"), 
          omit= c("IND1990", "YEAR"),
          omit.labels = c("Industry FE?", "Year FE?"),
          intercept.bottom = FALSE, 
          df = FALSE,
          model.names = FALSE, 
          column.labels =c("No Controls", "With Controls", "No Controls", "With Controls",
          dep.var.labels.include = FALSE,
          order =c(1, 2, 3, 4),
          covariate.labels =c("$Constant$", "$Post$", "$AI$", "$AI:Post$", "$Frac. College$",
                              "$Frac. White$", "$Frac. Female$", "$Age$")))

```

Secretaries DiD Regressions: 

```{r secretaries}
# Wage DiD for Secretaries vs. Aides
sa_wage_did1 <- lm(LOGWAGE ~ AI + AIPost + factor(YEAR) + factor(IND1990), data = sa_wage)
sa_wage_did2 <- lm(LOGWAGE ~ AI + AIPost + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(YEAR) + factor(IND1990), data = sa_wage) 

# Employment DiD for Secretaries vs. Aides
sa_emp_did1 <- lm(LOGEMP ~ AI + AIPost + factor(YEAR) + factor(IND1990), data = sa_emp)
sa_emp_did2 <- lm(LOGEMP ~ AI + AIPost + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(YEAR) + factor(IND1990), data = sa_emp)
```

```{r secretaries2}
summary(sa_emp_did2)
```
```{r stargazer2, echo = TRUE, message=FALSE, warning=FALSE, results='asis'}
stargazer(sa_wage_did1, sa_wage_did2, sa_emp_did1, sa_emp_did2,
          type = "latex", header=FALSE, 
          column.sep.width = "0.1pt",
          omit.stat =c("f", "ser"), 
          omit= c("YEAR", "IND1990"),
          omit.labels = c("Year FE?", "Industry FE?"),
          intercept.bottom = FALSE, 
          df = FALSE,
          model.names = FALSE, 
          column.labels =c("No Controls", "With Controls", "No Controls", "With Controls",
          dep.var.labels.include = FALSE,
          order =c(1, 2, 3, 4),
          covariate.labels =c("$Constant$", "$Post$", "$AI$", "$AI:Post$", "$Frac. College$",
                              "$Frac. White$", "$Frac. Female$", "$Age$")))

```

```{r vifs}
car::vif(sa_emp_did2)
```












