---
title: "OLS Regressions"
output: html_notebook
---

This is a notebook that runs the regressions for all of the OLS
regressions for my honors thesis project. 

```{r libraries}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(stargazer)
library(plm)
library(regclass)
```

Importing Relevant Datasets: 

```{r data}
p_wage_ols <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/p_wage_ols.csv",header =  TRUE)
s_wage_ols <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/s_wage_ols.csv",header =  TRUE)
a_wage_ols <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/a_wage_ols.csv",header =  TRUE)

p_emp_ols <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/p_emp_ols.csv",header =  TRUE)
s_emp_ols <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/s_emp_ols.csv",header =  TRUE)
a_emp_ols <-read.csv(file = "/Users/sidsatya/Desktop/berkeley/senior_year/thesis/aithesis/data/a_emp_ols.csv",header =  TRUE)
```

Wage Regressions: 

```{r wages}
# Wage DiD for Physicians vs. Aides
p_wage_ols = p_wage_ols
pwagereg1 <- lm(LOGWAGE ~ num_patents, data=p_wage_ols)
pwagereg2 <- lm(LOGWAGE ~ num_patents + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(IND1990), data=p_wage_ols)

swagereg1 <- lm(LOGWAGE ~ num_patents, data=s_wage_ols)
swagereg2 <- lm(LOGWAGE ~ num_patents + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(IND1990), data=s_wage_ols)

awagereg1 <- lm(LOGWAGE ~ num_patents, data=a_wage_ols)
awagereg2 <- lm(LOGWAGE ~ num_patents + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(IND1990), data=a_wage_ols)
```

```{r stargazer1, echo = TRUE, message=FALSE, warning=FALSE, results='asis'}
stargazer(pwagereg2, swagereg2, awagereg2,
          type = "latex", header=FALSE, 
          column.sep.width = "0.1pt",
          omit.stat =c("f", "ser"), 
          omit=c("IND1990"),
          omit.labels=c("Industry FE?"),
          intercept.bottom = FALSE, 
          df = FALSE,
          model.names = FALSE, 
          column.labels =c("Physicians and Surgeons", "Secretaries & Administrative Assistants", "Health Aides",
          dep.var.labels.include = FALSE,
          order =c(1, 2, 3, 4),
          covariate.labels =c("$Constant$", "$Num. AI Patents", "$Frac. College$",
                              "$Frac. White$", "$Frac. Female$", "$Age$")))

```
Employment Regressions: 

```{r emp}
pempreg1 <- lm(LOGEMP ~ num_patents, data=p_emp_ols)
pempreg2 <- lm(LOGEMP ~ num_patents + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(IND1990), data=p_emp_ols)

sempreg1 <- lm(LOGEMP ~ num_patents, data=s_emp_ols)
sempreg2 <- lm(LOGEMP ~ num_patents + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(IND1990), data=s_emp_ols)

aempreg1 <- lm(LOGEMP ~ num_patents, data=a_emp_ols)
aempreg2 <- lm(LOGEMP ~ num_patents + FRACCOLLEGE + FRACWHITE + FRACFEMALE + AGE + factor(IND1990), data=a_emp_ols)
```

```{r stargazer2, echo = TRUE, message=FALSE, warning=FALSE, results='asis'}
stargazer(pempreg2, sempreg2, aempreg2,
          type = "latex", header=FALSE, 
          column.sep.width = "0.1pt",
          omit.stat =c("f", "ser"), 
          omit=c("IND1990"),
          omit.labels=c("Industry FE?"),
          intercept.bottom = FALSE, 
          df = FALSE,
          model.names = FALSE, 
          column.labels =c("Physicians and Surgeons", "Secretaries & Administrative Assistants", "Health Aides",
          dep.var.labels.include = FALSE,
          order =c(1, 2, 3, 4),
          covariate.labels =c("$Constant$", "$Num. AI Patents", "$Frac. College$",
                              "$Frac. White$", "$Frac. Female$", "$Age$")))

```






```{r vifs}
car::vif(pempreg2)
```













